Продолжение игры за монеты
TheNech/RollingSphere pull request #20
Opened 2017-12-20 20:10 UTC by vinarut

2017-12-22 17:54 UTC, TheNech commented
Этот комментарий видно?

2017-12-22 19:56 UTC, d3m1d0v requested changes

2017-12-22 19:56 UTC, d3m1d0v commented on www/js/registration.js
> +  repeatPass.trim();
Метод trim() не изменяет значение текущей строки, а возвращает новую с вырезанными пробелами по концам

2017-12-22 19:56 UTC, d3m1d0v commented on www/js/registration.js
> +  } else {
Спагетти-код. Лучше переписать на
if(condition1) {
    // some code
    return;
}
if(condition2) {
    // some code
    return;
}

И т.д.

2017-12-22 19:56 UTC, d3m1d0v commented on www/js/socket.js
> +socket.on('new-global-top-score', function(data){
Все подписки можно чейнить:
socket
    .on('message1', function(){})
    .on('message2', function(){})
    .on('message3', function(){});

2017-12-22 19:56 UTC, d3m1d0v commented on www/js/registration.js
> +        if ($('#validationReg').hasClass('error')) {
Плохая читабельность. Лучше переписать на:
if (!data.successfully) {
// some code
return;
}
// код при успешной регистрации далее

2017-12-22 19:56 UTC, d3m1d0v commented on www/js/registration.js
> +            $('#validationReg').addClass('success');
Продублированный код в if и else:
$('#validationReg').addClass('success');

2017-12-22 19:56 UTC, d3m1d0v commented on www/js/authorization.js
> +    }
Много кода в if и мало в else => плохая читабельность. Лучше переписать на
if(!data.successfully){
document.getElementById('validationAuth').style.display = 'block';
 document.getElementById('validationAuth').innerHTML = 'Authorization failed! Please enter correct data';
$('#validationAuth').addClass('error');
return;
}

// код при успешной авторизации

2017-12-22 19:56 UTC, d3m1d0v commented on www/js/registration.js
> +    $('#validationReg').addClass('error');
В каждом if практически один и тот-же код. Отличаются только выводимый текст. Лучше весь этот общий код вынести в отдельную функцию, которая в качестве параметра принимает текстовое сообщение

2017-12-22 19:56 UTC, d3m1d0v commented on www/js/socket.js
> +})
Сообщения "connected" больше нет

2017-12-23 07:13 UTC, d3m1d0v requested changes

2017-12-23 07:13 UTC, d3m1d0v commented on www/js/authorization.js
> +  socket.on('auth', function (data) {
подписка на сообщение внутри обработчика нажатия кнопки. Либо в `if` выше нужно добавить `return;`, либо сделать чтобы только при первом нажатии происходила подписка

2017-12-23 07:13 UTC, d3m1d0v commented on www/js/socket.js
> +.on('player-disconnected', function(data) {
Этих сообщений больше нет (см. readme)

2017-12-25 11:07 UTC, TheNech approved these changes

2017-12-25 11:07 UTC, merged

2017-12-25 16:46 UTC, d3m1d0v commented
вы акуели здесь? какого куя без моего подтверждения смёржили?